#!/bin/bash

##
## Defaults
##

default_repo=aiegoo/hanuman

##
## Sanity checks
##

if [[ ! $1 ]] || [[ $1 == ' ' ]]; then
    echo "No repository name specified, using the default one"
else
    default_repo=$1
fi

##
## Log what's happening
##

mkdir -p logs
log_file=logs/update-$(date +%Y%m%d-%H%M%S).log
exec > >(tee $log_file) 2>&1
echo "Capturing output to $log_file"
echo "Update started at $(date '+%Y-%m-%d %H:%M:%S')"

function finish {
    echo "Update finished at $(date '+%Y-%m-%d %H:%M:%S')"
}

trap finish EXIT

echo "Updating repo '$default_repo' on all servers"

cd /root/ansible/playbooks && sudo -E ansible-playbook -vvv ./update.yml \
 -i inventory.ini \
# --extra-vars "GITHUB_REPO_NAME='$default_repo'"

ansible_status=$?

if [[ $ansible_status -ne 0 ]]; then
    echo " "
    echo "========================================"
    echo "Ansible failed!"
    echo "----------------------------------------"
    echo "    Your log file is at $log_file"
    echo "    Your environment:"
    env | egrep -i 'version|release' | sed -e 's/^/        /'
    echo "========================================"
fi
